
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardpj
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: '/webapp/**'
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
